---
title: "Data Exploration"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(hms)
```

```{r}
#df1 <- read_csv("data/marathon-data.csv")
#names(df)[3] <- "firstHalf"
df1 <- read_tsv("data/marathon_wide.tsv")
head(df)
```

```{r}
secs_per_mile <- function(x, distance){
  secs <- (3600 * hour(x)) + (60 * minute(x)) + second(x)
  secs_per_mile <- secs / distance
  return(secs_per_mile)
}

is_bq <- function(x, gender, age){
  if(gender == "M"){
    if(age <= 35 & x < hms::hms(00, 5, 3)) return(1)
    else if( age > 35 & age <= 39 & x < hms::hms(00, 10, 3)) return(1)
    else if( age > 39 & age <= 44 & x < hms::hms(00, 15, 3)) return(1)
    else if( age > 44 & age <= 49 & x < hms::hms(00, 25, 3)) return(1)
    else if( age > 49 & age <= 54 & x < hms::hms(00, 30, 3)) return(1)
    else if( age > 54 & age <= 59 & x < hms::hms(00, 40, 3)) return(1)
    else if( age > 59 & age <= 64 & x < hms::hms(00, 55, 3)) return(1)
    else if( age > 64 & age <= 69 & x < hms::hms(00, 10, 4)) return(1)
    else if( age > 69 & age <= 74 & x < hms::hms(00, 25, 4)) return(1)
    else if( age > 74 & age <= 79 & x < hms::hms(00, 40, 4)) return(1)
    else if( age > 79 & x < hms::hms(00, 55, 4)) return(1)
    else return(0)
  } else {
    if(age <= 34 & x < hms::hms(00, 35, 3)) return(1)
    else if( age > 34 & age <= 39 & x < hms::hms(00, 40, 3)) return(1)
    else if( age > 39 & age <= 44 & x < hms::hms(00, 45, 3)) return(1)
    else if( age > 44 & age <= 49 & x < hms::hms(00, 55, 3)) return(1)
    else if( age > 49 & age <= 54 & x < hms::hms(00, 00, 4)) return(1)
    else if( age > 54 & age <= 59 & x < hms::hms(00, 10, 4)) return(1)
    else if( age > 59 & age <= 64 & x < hms::hms(00, 25, 4)) return(1)
    else if( age > 64 & age <= 69 & x < hms::hms(00, 40, 4)) return(1)
    else if( age > 69 & age <= 74 & x < hms::hms(00, 55, 4)) return(1)
    else if( age > 74 & age <= 79 & x < hms::hms(00, 10, 5)) return(1)
    else if( age > 79 & x < hms::hms(00, 25, 5)) return(1)
    else return(0)
  }
}

#df1 <- df1 %>% mutate(halfPace = secs_per_mile(firstHalf, 13.1),
#                    fullPace = secs_per_mile(final, 26.2),
#                    secondHalf = hms::hms(as.numeric(final - firstHalf)),
#                    secondHalfPace = secs_per_mile(secondHalf, 13.1))
#df1 <- df1 %>% 
#  rowwise() %>% 
#  mutate(BQ = is_bq(final, gender, age))

#df1['diffPace'] <- df1$secondHalfPace - df1$halfPace
#df1['ID'] <- seq(1, length(df1$age))

# q10M <- df1 %>% filter(gender == "M") %>% pull(fullPace) %>% quantile(0.10)
# q10W <- df1 %>% filter(gender == "W") %>% pull(fullPace) %>% quantile(0.10)
# 
# in_top_10 <- function(x, gender){
#   if(gender == "M" & x <= q10M) return(1)
#   else if (gender == "W" & x <= q10W) return(1)
#   else return(0)
# }
# 
# df1 <- df1 %>%
#   rowwise() %>%
#   mutate(top10Q = in_top_10(fullPace, gender))

#write.table(df, file = "data/marathon_wide.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```

# Histograms

```{r}
df1 %>% ggplot(aes(x = halfPace)) + geom_histogram() +
  scale_x_continuous(name = "Half Time (pace/mile)", breaks = c(250, 500, 750, 1000, 1250), 
                     labels = c("54:35 (4:10)", "1:49:10 (8:20)", "2:43:35 (12:30)", "3:38:20 (16:40)", "4:32:55 (20:50)")) +
  ylab("Frequency") + ggtitle("Half Marathon Split Times")
```

```{r}
df1 %>% ggplot(aes(x = fullPace)) + geom_histogram()  +
  scale_x_continuous(name = "Full Time (pace/mile)", breaks = c(250, 500, 750, 1000, 1250), 
                     labels = c("1:49:10 (4:10)", "3:38:20 (8:20)", "5:27:30 (12:30)", "7:16:40 (16:40)", "9:05:50 (20:50)")) +
  ylab("Frequency") + ggtitle("Marathon Times")
```

```{r}
df1 %>% ggplot(aes(x = diffPace)) + geom_histogram()
```

# Tall Data

```{r}
df1["ageN"] <- scale(df1$age)
df_tall <- df1 %>% select(ID, ageN, gender, BQ, fullPace, halfPace, secondHalfPace) %>%
  gather(segment, pace, halfPace:secondHalfPace)

head(df_tall)
```
```{r}
df_tall['rel_pace'] <- df_tall$pace / df_tall$fullPace
df_tall %>% filter(segment == "halfPace") %>% ggplot(aes(x = rel_pace)) + geom_histogram()
```

# Models

```{r}
library(geepack)

df_tall['RelPace'] <- df_tall$pace / df_tall$fullPace

# Test the effect of smoke using anova
fit1 <- geeglm(log(RelPace) ~ ageN + factor(gender) + factor(BQ) + factor(segment), family = gaussian(),
               data = df_tall, id = ID, corstr = "exchangeable")

fit2 <- geeglm(RelPace ~ ageN + factor(gender) + factor(BQ) + factor(segment), family = gaussian(),
               data = df_tall, id = ID, corstr = "independence")

anova(fit1, fit2)

df1['relDiff'] <- df1$diffPace / df1$fullPace
df1['ageN2'] <- df1$ageN ** 2
fit4 <- glm(relDiff ~ ageN + factor(gender) + factor(BQ) + factor(top10Q) + ageN2, 
            data = df1, family = gaussian())

# Ward-inspired model
fit1 <- glm(relDiff ~ factor(gender) + ageN + factor(BQ) + factor(top10Q) +
              ageN * factor(gender) + ageN * factor(BQ) + factor(gender) * factor(BQ)+
              ageN2, data=df1)
```

